import type { GuidedAnswerType, GuidedRequiredLevel, GuidedSetupSection, ScriptImpact } from "@prisma/client";

/**
 * The configurable Guided Setup question catalog (spec sections 9–16). This
 * is the seed source for `GuidedSetupQuestionDefinition` rows — the flow is
 * never hardcoded in a React component. Every entry must pass
 * `validateQuestionScriptImpact` (enforced by a unit test and at seed time).
 *
 * Destination mapping deliberately reuses existing normalized entities
 * (Cohort, CommercialSituation, BeliefMap, ClientBrainItem, the new Offer/
 * ProofItem) wherever one exists, rather than inventing a parallel store —
 * per spec section 21 ("do not duplicate the complete Client Brain").
 */
export type ConditionalLogic = { dependsOnKey: string; equals?: string | boolean; notEquals?: string | boolean } | null;

export type QuestionOption = { value: string; label: string };

export type QuestionCatalogEntry = {
  key: string;
  section: GuidedSetupSection;
  userFacingQuestion: string;
  helperText: string | null;
  example: string | null;
  answerType: GuidedAnswerType;
  options: QuestionOption[] | null;
  requiredLevel: GuidedRequiredLevel;
  scriptImpacts: ScriptImpact[];
  destinationEntity: string | null;
  destinationField: string | null;
  conditionalLogic: ConditionalLogic;
  plainLanguageLabel: string | null;
  expertLabel: string | null;
  displayOrder: number;
};

let order = 0;
function next(): number {
  order += 10;
  return order;
}

export const SECTION_LABELS: Record<GuidedSetupSection, string> = {
  BUSINESS: "The Business",
  AUDIENCE: "The Audience",
  BELIEF_DECISION: "The Belief and Decision",
  OFFER: "The Offer",
  PROOF: "The Proof",
  VOICE: "The Voice",
  EXECUTION: "Reel Execution",
  SAFETY: "Safety and Constraints",
  FINAL_REVIEW: "Final Review",
};

export const QUESTION_CATALOG: QuestionCatalogEntry[] = [
  // ---- Section 1: The Business ----
  {
    key: "business.client_name",
    section: "BUSINESS",
    userFacingQuestion: "What is the client or brand name?",
    helperText: null,
    example: "Kamal Ghamry",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["SYSTEM_ONLY"],
    destinationEntity: "Client",
    destinationField: "displayName",
    conditionalLogic: null,
    plainLanguageLabel: "Client name",
    expertLabel: "Client.displayName",
    displayOrder: next(),
  },
  {
    key: "business.brand_type",
    section: "BUSINESS",
    userFacingQuestion: "Is this a person, a company, or both?",
    helperText: "This changes how the script talks about who is speaking.",
    example: "A solo consultant is usually a Personal brand.",
    answerType: "SINGLE_SELECT",
    options: [
      { value: "PERSONAL_BRAND", label: "Personal brand" },
      { value: "COMPANY_BRAND", label: "Company" },
      { value: "HYBRID", label: "Hybrid" },
    ],
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["VOICE", "STORY", "PROOF"],
    destinationEntity: "Client",
    destinationField: "brandType",
    conditionalLogic: null,
    plainLanguageLabel: "Personal, company, or both?",
    expertLabel: "Client.brandType",
    displayOrder: next(),
  },
  {
    key: "business.what_they_sell",
    section: "BUSINESS",
    userFacingQuestion: "What do they sell?",
    helperText: "In plain terms — what does a customer actually get?",
    example: "A one-session marketing decision consultation for CEOs.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["BODY", "CTA", "ANGLE"],
    destinationEntity: "ClientBrainItem",
    destinationField: "BUSINESS:PRODUCTS_SERVICES",
    conditionalLogic: null,
    plainLanguageLabel: "What do they sell?",
    expertLabel: "ClientBrainItem(BUSINESS.PRODUCTS_SERVICES)",
    displayOrder: next(),
  },
  {
    key: "business.content_objective",
    section: "BUSINESS",
    userFacingQuestion: "What is the main objective of their content?",
    helperText: "This shapes what every Reel is trying to accomplish.",
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "AWARENESS", label: "Make more people aware" },
      { value: "TRUST", label: "Build trust" },
      { value: "EDUCATION", label: "Educate the market" },
      { value: "BELIEF_CHANGE", label: "Change an important belief" },
      { value: "OBJECTION_HANDLING", label: "Support the sales team" },
      { value: "OFFER_PROMOTION", label: "Generate qualified leads, bookings, or purchases" },
    ],
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["ANGLE", "CTA", "BODY"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "content_objective",
    conditionalLogic: null,
    plainLanguageLabel: "Main content objective",
    expertLabel: "ScriptIntelligenceField(content_objective)",
    displayOrder: next(),
  },
  {
    key: "business.market",
    section: "BUSINESS",
    userFacingQuestion: "Which market do they mainly serve?",
    helperText: "Only matters if it changes language, examples, or claims — skip it otherwise.",
    example: "Egypt",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["AUDIENCE", "EXAMPLE", "VOICE", "SAFETY"],
    destinationEntity: "ClientBrainItem",
    destinationField: "MARKETS:MARKET_NAME",
    conditionalLogic: null,
    plainLanguageLabel: "Main market",
    expertLabel: "ClientBrainItem(MARKETS.MARKET_NAME)",
    displayOrder: next(),
  },

  // ---- Section 2: The Audience ----
  {
    key: "audience.who",
    section: "AUDIENCE",
    userFacingQuestion: "Who should watch these videos?",
    helperText: "Describe the real situation they're in — not a demographic label.",
    example: "Marketing managers blamed for weak sales conversion.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["AUDIENCE"],
    destinationEntity: "Cohort",
    destinationField: "name",
    conditionalLogic: null,
    plainLanguageLabel: "Who should watch?",
    expertLabel: "Cohort.name",
    displayOrder: next(),
  },
  {
    key: "audience.role",
    section: "AUDIENCE",
    userFacingQuestion: "What role or situation describes them?",
    helperText: null,
    example: "Marketing Manager",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["AUDIENCE", "VOICE"],
    destinationEntity: "Cohort",
    destinationField: "role",
    conditionalLogic: null,
    plainLanguageLabel: "Their role",
    expertLabel: "Cohort.role",
    displayOrder: next(),
  },
  {
    key: "audience.active_problem",
    section: "AUDIENCE",
    userFacingQuestion: "What is happening to them now?",
    helperText: "The specific, painful problem — what problem are they trying to solve?",
    example: "Marketing generates leads, but sales says the leads are not qualified.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["BODY", "ANGLE"],
    destinationEntity: "CommercialSituation",
    destinationField: "activeProblem",
    conditionalLogic: null,
    plainLanguageLabel: "What is happening now?",
    expertLabel: "CommercialSituation.activeProblem",
    displayOrder: next(),
  },
  {
    key: "audience.trigger",
    section: "AUDIENCE",
    userFacingQuestion: "What made this issue important right now?",
    helperText: null,
    example: "The monthly revenue target was missed.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["ANGLE", "STORY"],
    destinationEntity: "CommercialSituation",
    destinationField: "triggerDescription",
    conditionalLogic: null,
    plainLanguageLabel: "What triggered it?",
    expertLabel: "CommercialSituation.triggerDescription",
    displayOrder: next(),
  },
  {
    key: "audience.current_workflow",
    section: "AUDIENCE",
    userFacingQuestion: "What are they currently doing about it?",
    helperText: null,
    example: "Pressuring marketing to generate more leads or lower cost-per-lead.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["BODY", "REFRAME"],
    destinationEntity: "Cohort",
    destinationField: "currentWorkflow",
    conditionalLogic: null,
    plainLanguageLabel: "What are they doing about it?",
    expertLabel: "Cohort.currentWorkflow",
    displayOrder: next(),
  },
  {
    key: "audience.desired_outcome",
    section: "AUDIENCE",
    userFacingQuestion: "What result do they want?",
    helperText: null,
    example: "Prove marketing's commercial impact to a skeptical CEO.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["CTA", "ANGLE"],
    destinationEntity: "Cohort",
    destinationField: "desiredOutcome",
    conditionalLogic: null,
    plainLanguageLabel: "What result do they want?",
    expertLabel: "Cohort.desiredOutcome",
    displayOrder: next(),
  },
  {
    key: "audience.decision_risk",
    section: "AUDIENCE",
    userFacingQuestion: "What is stopping them, or what are they afraid might happen?",
    helperText: null,
    example: "Budget could be cut if next quarter doesn't show results.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["ANGLE", "SAFETY"],
    destinationEntity: "Cohort",
    destinationField: "decisionRisk",
    conditionalLogic: null,
    plainLanguageLabel: "What's stopping them?",
    expertLabel: "Cohort.decisionRisk",
    displayOrder: next(),
  },
  {
    key: "audience.exact_language",
    section: "AUDIENCE",
    userFacingQuestion: "What exact words do they use when describing the problem?",
    helperText: "Real phrases beat polished marketing language.",
    example: "\"We keep scaling ROAS but the CEO says we still aren't making more money.\"",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["EXAMPLE", "VOICE"],
    destinationEntity: "Cohort",
    destinationField: "attentionNotes",
    conditionalLogic: null,
    plainLanguageLabel: "Their exact words",
    expertLabel: "Cohort.attentionNotes",
    displayOrder: next(),
  },
  {
    key: "audience.platform",
    section: "AUDIENCE",
    userFacingQuestion: "Where do they usually consume this kind of content?",
    helperText: null,
    example: "LinkedIn, Instagram",
    answerType: "MULTI_SELECT",
    options: [
      { value: "Instagram", label: "Instagram" },
      { value: "LinkedIn", label: "LinkedIn" },
      { value: "TikTok", label: "TikTok" },
      { value: "YouTube", label: "YouTube" },
      { value: "Facebook", label: "Facebook" },
      { value: "Email", label: "Email" },
    ],
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["FORMAT", "VISUAL"],
    destinationEntity: "Cohort",
    destinationField: "platformPresence",
    conditionalLogic: null,
    plainLanguageLabel: "Where they spend attention",
    expertLabel: "Cohort.platformPresence",
    displayOrder: next(),
  },

  // ---- Section 3: The Belief and Decision ----
  {
    key: "belief.observed_situation",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What actually happened?",
    helperText: null,
    example: "Sales conversion dropped while marketing hit its lead targets.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["REFRAME"],
    destinationEntity: "BeliefMap",
    destinationField: "observedSituation",
    conditionalLogic: null,
    plainLanguageLabel: "What happened?",
    expertLabel: "BeliefMap.observedSituation",
    displayOrder: next(),
  },
  {
    key: "belief.current_interpretation",
    section: "BELIEF_DECISION",
    userFacingQuestion: "Why does that belief appear reasonable to them?",
    helperText: null,
    example: "Leadership assumes marketing failed because the topline number is down.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["REFRAME"],
    destinationEntity: "BeliefMap",
    destinationField: "currentInterpretation",
    conditionalLogic: null,
    plainLanguageLabel: "Why it seems reasonable",
    expertLabel: "BeliefMap.currentInterpretation",
    displayOrder: next(),
  },
  {
    key: "belief.current_belief",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What do they currently think is causing the problem?",
    helperText: "State the belief precisely — this is what the Reel will challenge.",
    example: "Weak sales conversion means the lead quality is poor.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["REFRAME", "ANGLE"],
    destinationEntity: "BeliefMap",
    destinationField: "currentBeliefStatement",
    conditionalLogic: null,
    plainLanguageLabel: "What do they currently think?",
    expertLabel: "BeliefMap.currentBeliefStatement",
    displayOrder: next(),
  },
  {
    key: "belief.behavior_caused",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What do they do because of this belief?",
    helperText: null,
    example: "Management pressures marketing to generate more leads or reduce cost-per-lead.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["STORY", "BODY"],
    destinationEntity: "BeliefMap",
    destinationField: "behaviorCaused",
    conditionalLogic: null,
    plainLanguageLabel: "What they do about it",
    expertLabel: "BeliefMap.behaviorCaused",
    displayOrder: next(),
  },
  {
    key: "belief.commercial_consequence",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What commercial consequence follows?",
    helperText: null,
    example: "More advertising budget is spent before diagnosing the real conversion constraint.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["BODY", "STORY"],
    destinationEntity: "BeliefMap",
    destinationField: "commercialConsequence",
    conditionalLogic: null,
    plainLanguageLabel: "What it costs them",
    expertLabel: "BeliefMap.commercialConsequence",
    displayOrder: next(),
  },
  {
    key: "belief.better_belief",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What should they understand instead?",
    helperText: "Must be a genuinely different, developed idea — not a one-word opposite.",
    example: "Weak conversion may come from targeting, qualification, follow-up, pricing, or offer design — not just lead quality.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["REFRAME"],
    destinationEntity: "BeliefMap",
    destinationField: "betterBeliefStatement",
    conditionalLogic: null,
    plainLanguageLabel: "The better understanding",
    expertLabel: "BeliefMap.betterBeliefStatement",
    displayOrder: next(),
  },
  {
    key: "belief.better_decision",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What should they do differently?",
    helperText: null,
    example: "Diagnose the complete lead-to-revenue journey before increasing lead volume.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["CTA", "ANGLE"],
    destinationEntity: "BeliefMap",
    destinationField: "betterCommercialDecision",
    conditionalLogic: null,
    plainLanguageLabel: "The better decision",
    expertLabel: "BeliefMap.betterCommercialDecision",
    displayOrder: next(),
  },
  {
    key: "belief.evidence",
    section: "BELIEF_DECISION",
    userFacingQuestion: "What evidence supports the better understanding?",
    helperText: "It's fine to say you don't have this yet.",
    example: "A client increased contribution profit by 22% after cutting a high-ROAS, poor-lead-quality campaign.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["PROOF"],
    destinationEntity: "EvidenceLink",
    destinationField: "description",
    conditionalLogic: null,
    plainLanguageLabel: "Supporting evidence",
    expertLabel: "EvidenceLink.description",
    displayOrder: next(),
  },

  // ---- Section 4: The Offer (conditional — educational Reels don't need one) ----
  {
    key: "offer.has_offer",
    section: "OFFER",
    userFacingQuestion: "Is there an offer to mention in this content?",
    helperText: "Choose \"Not selling anything yet\" for purely educational content.",
    example: null,
    answerType: "BOOLEAN",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["CTA"],
    destinationEntity: "Offer",
    destinationField: "hasOffer",
    conditionalLogic: null,
    plainLanguageLabel: "Is there an offer?",
    expertLabel: "Offer(exists)",
    displayOrder: next(),
  },
  {
    key: "offer.name",
    section: "OFFER",
    userFacingQuestion: "What is the offer called?",
    helperText: null,
    example: "CEO Marketing Decision Session",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["CTA", "ANGLE"],
    destinationEntity: "Offer",
    destinationField: "name",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Offer name",
    expertLabel: "Offer.name",
    displayOrder: next(),
  },
  {
    key: "offer.for_whom",
    section: "OFFER",
    userFacingQuestion: "Who is it for?",
    helperText: null,
    example: null,
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["AUDIENCE", "CTA"],
    destinationEntity: "Offer",
    destinationField: "forWhom",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Who it's for",
    expertLabel: "Offer.forWhom",
    displayOrder: next(),
  },
  {
    key: "offer.problem_addressed",
    section: "OFFER",
    userFacingQuestion: "What problem does it address?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["BODY", "ANGLE"],
    destinationEntity: "Offer",
    destinationField: "problemAddressed",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Problem it addresses",
    expertLabel: "Offer.problemAddressed",
    displayOrder: next(),
  },
  {
    key: "offer.intended_outcome",
    section: "OFFER",
    userFacingQuestion: "What outcome does it help create?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["CTA", "BODY"],
    destinationEntity: "Offer",
    destinationField: "intendedOutcome",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Outcome it creates",
    expertLabel: "Offer.intendedOutcome",
    displayOrder: next(),
  },
  {
    key: "offer.mechanism",
    section: "OFFER",
    userFacingQuestion: "How does it create that outcome?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["BODY"],
    destinationEntity: "Offer",
    destinationField: "mechanism",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "How it works",
    expertLabel: "Offer.mechanism",
    displayOrder: next(),
  },
  {
    key: "offer.deliverables",
    section: "OFFER",
    userFacingQuestion: "What does the customer receive?",
    helperText: "List each thing on its own line.",
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["BODY", "CTA"],
    destinationEntity: "Offer",
    destinationField: "deliverables",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "What they receive",
    expertLabel: "Offer.deliverables",
    displayOrder: next(),
  },
  {
    key: "offer.price_presentation",
    section: "OFFER",
    userFacingQuestion: "What does it cost?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "NOT_SELLING_YET", label: "Not selling anything yet" },
      { value: "DO_NOT_MENTION_PRICE", label: "Do not mention price publicly" },
      { value: "CUSTOM_QUOTATION", label: "Custom quotation" },
      { value: "STARTING_FROM", label: "Starting from" },
      { value: "EXACT_PRICE", label: "Exact price" },
      { value: "PRICE_RANGE", label: "Price range" },
      { value: "FREE", label: "Free" },
    ],
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["CTA", "SAFETY"],
    destinationEntity: "Offer",
    destinationField: "pricePresentation",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Price presentation",
    expertLabel: "Offer.pricePresentation",
    displayOrder: next(),
  },
  {
    key: "offer.excluded_outcomes",
    section: "OFFER",
    userFacingQuestion: "What does it not guarantee?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "Offer",
    destinationField: "excludedOutcomes",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "What it doesn't guarantee",
    expertLabel: "Offer.excludedOutcomes",
    displayOrder: next(),
  },
  {
    key: "offer.cta_route",
    section: "OFFER",
    userFacingQuestion: "What should an interested viewer do next?",
    helperText: null,
    example: "Book a diagnostic session.",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_COMMERCIAL_REEL",
    scriptImpacts: ["CTA"],
    destinationEntity: "Offer",
    destinationField: "ctaRoute",
    conditionalLogic: { dependsOnKey: "offer.has_offer", equals: true },
    plainLanguageLabel: "Next step for the viewer",
    expertLabel: "Offer.ctaRoute",
    displayOrder: next(),
  },

  // ---- Section 5: The Proof ----
  {
    key: "proof.has_proof",
    section: "PROOF",
    userFacingQuestion: "Do you have proof the audience should see?",
    helperText: "It's fine to say no — the Reel can use reasoning instead.",
    example: null,
    answerType: "BOOLEAN",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["PROOF"],
    destinationEntity: "ProofItem",
    destinationField: "hasProof",
    conditionalLogic: null,
    plainLanguageLabel: "Any proof available?",
    expertLabel: "ProofItem(exists)",
    displayOrder: next(),
  },
  {
    key: "proof.type",
    section: "PROOF",
    userFacingQuestion: "What kind of proof is it?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "CASE_STUDY", label: "Case study" },
      { value: "RESULT", label: "Result" },
      { value: "TESTIMONIAL", label: "Testimonial" },
      { value: "EXPERIENCE", label: "Experience" },
      { value: "CREDENTIAL", label: "Credential" },
      { value: "FRAMEWORK", label: "Framework" },
      { value: "PROCESS", label: "Process" },
      { value: "DEMONSTRATION", label: "Demonstration" },
      { value: "SCREENSHOT", label: "Screenshot" },
      { value: "ARTIFACT", label: "Artifact" },
      { value: "CUSTOMER_EXAMPLE", label: "Customer example" },
    ],
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["PROOF"],
    destinationEntity: "ProofItem",
    destinationField: "proofType",
    conditionalLogic: { dependsOnKey: "proof.has_proof", equals: true },
    plainLanguageLabel: "Type of proof",
    expertLabel: "ProofItem.proofType",
    displayOrder: next(),
  },
  {
    key: "proof.summary",
    section: "PROOF",
    userFacingQuestion: "Why should the audience believe this?",
    helperText: "What happened, for whom, what changed, and over what period.",
    example: "A client increased contribution profit by 22% within one quarter after cutting a high-ROAS, poor-lead-quality campaign.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["PROOF", "EXAMPLE"],
    destinationEntity: "ProofItem",
    destinationField: "whatHappened",
    conditionalLogic: { dependsOnKey: "proof.has_proof", equals: true },
    plainLanguageLabel: "Proof summary",
    expertLabel: "ProofItem.whatHappened",
    displayOrder: next(),
  },
  {
    key: "proof.public_use_status",
    section: "PROOF",
    userFacingQuestion: "Can it be used publicly?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "PUBLIC", label: "Public" },
      { value: "PUBLIC_ANONYMOUS", label: "Public, anonymously" },
      { value: "INTERNAL_ONLY", label: "Internal only" },
      { value: "REQUIRES_APPROVAL", label: "Requires approval" },
      { value: "PROHIBITED", label: "Prohibited" },
    ],
    requiredLevel: "CONDITIONAL",
    scriptImpacts: ["SAFETY", "PROOF"],
    destinationEntity: "ProofItem",
    destinationField: "publicUseStatus",
    conditionalLogic: { dependsOnKey: "proof.has_proof", equals: true },
    plainLanguageLabel: "Can this be shown publicly?",
    expertLabel: "ProofItem.publicUseStatus",
    displayOrder: next(),
  },
  {
    key: "proof.limitations",
    section: "PROOF",
    userFacingQuestion: "What are its limitations?",
    helperText: "E.g. one client only, not independently verified, etc.",
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["SAFETY", "PROOF"],
    destinationEntity: "ProofItem",
    destinationField: "limitations",
    conditionalLogic: { dependsOnKey: "proof.has_proof", equals: true },
    plainLanguageLabel: "Limitations",
    expertLabel: "ProofItem.limitations",
    displayOrder: next(),
  },

  // ---- Section 6: The Voice ----
  {
    key: "voice.language",
    section: "VOICE",
    userFacingQuestion: "Which language should the scripts use?",
    helperText: null,
    example: "Arabic",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ClientBrainItem",
    destinationField: "VOICE:LANGUAGE",
    conditionalLogic: null,
    plainLanguageLabel: "Language",
    expertLabel: "ClientBrainItem(VOICE.LANGUAGE)",
    displayOrder: next(),
  },
  {
    key: "voice.dialect",
    section: "VOICE",
    userFacingQuestion: "Which dialect?",
    helperText: null,
    example: "Egyptian Arabic",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ClientBrainItem",
    destinationField: "VOICE:DIALECT",
    conditionalLogic: null,
    plainLanguageLabel: "Dialect",
    expertLabel: "ClientBrainItem(VOICE.DIALECT)",
    displayOrder: next(),
  },
  {
    key: "voice.tones",
    section: "VOICE",
    userFacingQuestion: "How should the client sound? (up to three)",
    helperText: null,
    example: null,
    answerType: "MULTI_SELECT",
    options: [
      { value: "Direct", label: "Direct" },
      { value: "Calm", label: "Calm" },
      { value: "Challenging", label: "Challenging" },
      { value: "Educational", label: "Educational" },
      { value: "Friendly", label: "Friendly" },
      { value: "Authoritative", label: "Authoritative" },
      { value: "Analytical", label: "Analytical" },
      { value: "Story-led", label: "Story-led" },
      { value: "Humorous", label: "Humorous" },
    ],
    requiredLevel: "REQUIRED_FOR_ANY_REEL",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ClientBrainItem",
    destinationField: "VOICE:TONE",
    conditionalLogic: null,
    plainLanguageLabel: "Tone",
    expertLabel: "ClientBrainItem(VOICE.TONE)",
    displayOrder: next(),
  },
  {
    key: "voice.technicality",
    section: "VOICE",
    userFacingQuestion: "How technical should the content be?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "VERY_SIMPLE", label: "Very simple" },
      { value: "SIMPLE_WITH_BUSINESS_TERMS", label: "Simple with business terms" },
      { value: "PROFESSIONAL", label: "Professional" },
      { value: "TECHNICAL", label: "Technical" },
    ],
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "voice_technicality",
    conditionalLogic: null,
    plainLanguageLabel: "How technical?",
    expertLabel: "ScriptIntelligenceField(voice_technicality)",
    displayOrder: next(),
  },
  {
    key: "voice.preferred_vocabulary",
    section: "VOICE",
    userFacingQuestion: "Which words or phrases should be used?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ClientBrainItem",
    destinationField: "VOICE:VOCABULARY",
    conditionalLogic: null,
    plainLanguageLabel: "Preferred wording",
    expertLabel: "ClientBrainItem(VOICE.VOCABULARY)",
    displayOrder: next(),
  },
  {
    key: "voice.prohibited_phrases",
    section: "VOICE",
    userFacingQuestion: "Which words or phrases should never be used?",
    helperText: null,
    example: "No exaggerated creator language.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["VOICE", "SAFETY"],
    destinationEntity: "ClientBrainItem",
    destinationField: "VOICE:PROHIBITED_PHRASES",
    conditionalLogic: null,
    plainLanguageLabel: "Prohibited wording",
    expertLabel: "ClientBrainItem(VOICE.PROHIBITED_PHRASES)",
    displayOrder: next(),
  },
  {
    key: "voice.good_example",
    section: "VOICE",
    userFacingQuestion: "Give one example that sounds right.",
    helperText: null,
    example: "مشكلة الـ ROAS مش إنه رقم غلط، المشكلة إنك بتطلب منه يجاوب على سؤال أكبر منه.",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "voice_good_example",
    conditionalLogic: null,
    plainLanguageLabel: "A good example",
    expertLabel: "ScriptIntelligenceField(voice_good_example)",
    displayOrder: next(),
  },
  {
    key: "voice.bad_example",
    section: "VOICE",
    userFacingQuestion: "Give one example that sounds wrong.",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "voice_bad_example",
    conditionalLogic: null,
    plainLanguageLabel: "A wrong-sounding example",
    expertLabel: "ScriptIntelligenceField(voice_bad_example)",
    displayOrder: next(),
  },
  {
    key: "voice.language_mixing",
    section: "VOICE",
    userFacingQuestion: "How should English and Arabic be mixed, if at all?",
    helperText: null,
    example: "Natural English business terminology mixed into Egyptian Arabic sentences.",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VOICE"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "voice_language_mixing",
    conditionalLogic: null,
    plainLanguageLabel: "Language mixing rule",
    expertLabel: "ScriptIntelligenceField(voice_language_mixing)",
    displayOrder: next(),
  },

  // ---- Section 7: Reel Execution ----
  {
    key: "execution.speaker",
    section: "EXECUTION",
    userFacingQuestion: "Who will appear in the videos?",
    helperText: null,
    example: "The client",
    answerType: "SHORT_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["VISUAL", "FORMAT"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PRODUCTION:TEAM",
    conditionalLogic: null,
    plainLanguageLabel: "Who appears on camera",
    expertLabel: "ClientBrainItem(PRODUCTION.TEAM)",
    displayOrder: next(),
  },
  {
    key: "execution.formats",
    section: "EXECUTION",
    userFacingQuestion: "Which formats can they record?",
    helperText: null,
    example: null,
    answerType: "MULTI_SELECT",
    options: [
      { value: "TALKING_HEAD", label: "Talking head" },
      { value: "VOICEOVER", label: "Voiceover" },
      { value: "INTERVIEW", label: "Interview" },
      { value: "SCREEN_RECORDING", label: "Screen recording" },
      { value: "CASE_BREAKDOWN", label: "Case breakdown" },
      { value: "VLOG", label: "Vlog" },
      { value: "SKIT", label: "Skit" },
      { value: "REACTION", label: "Reaction" },
      { value: "GREEN_SCREEN", label: "Green screen" },
    ],
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["FORMAT"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PRODUCTION:FORMATS",
    conditionalLogic: null,
    plainLanguageLabel: "Available formats",
    expertLabel: "ClientBrainItem(PRODUCTION.FORMATS)",
    displayOrder: next(),
    // default: Talking Head
  },
  {
    key: "execution.duration",
    section: "EXECUTION",
    userFacingQuestion: "Preferred duration?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "UNDER_30", label: "Under 30 seconds" },
      { value: "30_45", label: "30–45 seconds" },
      { value: "45_60", label: "45–60 seconds" },
      { value: "60_90", label: "60–90 seconds" },
    ],
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["FORMAT"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "execution_duration",
    conditionalLogic: null,
    plainLanguageLabel: "Preferred duration",
    expertLabel: "ScriptIntelligenceField(execution_duration)",
    displayOrder: next(),
    // default: 45-60 seconds
  },
  {
    key: "execution.resources",
    section: "EXECUTION",
    userFacingQuestion: "Which resources are available?",
    helperText: null,
    example: null,
    answerType: "MULTI_SELECT",
    options: [
      { value: "Phone", label: "Phone" },
      { value: "Camera", label: "Camera" },
      { value: "Microphone", label: "Microphone" },
      { value: "Editor", label: "Editor" },
      { value: "Designer", label: "Designer" },
      { value: "Studio", label: "Studio" },
      { value: "Existing footage", label: "Existing footage" },
      { value: "Props", label: "Props" },
    ],
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VISUAL"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PRODUCTION:EQUIPMENT",
    conditionalLogic: null,
    plainLanguageLabel: "Available resources",
    expertLabel: "ClientBrainItem(PRODUCTION.EQUIPMENT)",
    displayOrder: next(),
  },
  {
    key: "execution.cannot_show",
    section: "EXECUTION",
    userFacingQuestion: "Is there anything that cannot be shown?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VISUAL", "SAFETY"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PRODUCTION:PRODUCTION_CONSTRAINTS",
    conditionalLogic: null,
    plainLanguageLabel: "What can't be shown",
    expertLabel: "ClientBrainItem(PRODUCTION.PRODUCTION_CONSTRAINTS)",
    displayOrder: next(),
  },
  {
    key: "execution.editing_level",
    section: "EXECUTION",
    userFacingQuestion: "How complex can the editing be?",
    helperText: null,
    example: null,
    answerType: "SINGLE_SELECT",
    options: [
      { value: "SIMPLE", label: "Simple" },
      { value: "MODERATE", label: "Moderate" },
      { value: "ADVANCED", label: "Advanced" },
    ],
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["VISUAL"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PRODUCTION:EDITING_CAPACITY",
    conditionalLogic: null,
    plainLanguageLabel: "Editing complexity",
    expertLabel: "ClientBrainItem(PRODUCTION.EDITING_CAPACITY)",
    displayOrder: next(),
    // default: Moderate
  },

  // ---- Section 8: Safety and Constraints ----
  {
    key: "safety.never_claim",
    section: "SAFETY",
    userFacingQuestion: "What must never be claimed?",
    helperText: null,
    example: "Guaranteed revenue growth",
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "REQUIRED_FOR_COMMERCIAL_REEL",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "ClientBrainItem",
    destinationField: "PROHIBITED_CLAIMS:CLAIM",
    conditionalLogic: null,
    plainLanguageLabel: "Never claim",
    expertLabel: "ClientBrainItem(PROHIBITED_CLAIMS.CLAIM)",
    displayOrder: next(),
  },
  {
    key: "safety.legal_restrictions",
    section: "SAFETY",
    userFacingQuestion: "Are there legal, regulatory, or industry restrictions?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "ClientBrainItem",
    destinationField: "CONSTRAINTS:LEGAL",
    conditionalLogic: null,
    plainLanguageLabel: "Legal restrictions",
    expertLabel: "ClientBrainItem(CONSTRAINTS.LEGAL)",
    displayOrder: next(),
  },
  {
    key: "safety.avoid_topics",
    section: "SAFETY",
    userFacingQuestion: "Which topics should be avoided?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "safety_avoid_topics",
    conditionalLogic: null,
    plainLanguageLabel: "Topics to avoid",
    expertLabel: "ScriptIntelligenceField(safety_avoid_topics)",
    displayOrder: next(),
  },
  {
    key: "safety.testimonials_public",
    section: "SAFETY",
    userFacingQuestion: "Can testimonials and results be used publicly by default?",
    helperText: null,
    example: null,
    answerType: "BOOLEAN",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["SAFETY", "PROOF"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "safety_testimonials_public",
    conditionalLogic: null,
    plainLanguageLabel: "Testimonials public by default?",
    expertLabel: "ScriptIntelligenceField(safety_testimonials_public)",
    displayOrder: next(),
  },
  {
    key: "safety.requires_approval",
    section: "SAFETY",
    userFacingQuestion: "Does content require approval before publishing?",
    helperText: null,
    example: null,
    answerType: "BOOLEAN",
    options: null,
    requiredLevel: "RECOMMENDED",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "safety_requires_approval",
    conditionalLogic: null,
    plainLanguageLabel: "Requires approval before publishing?",
    expertLabel: "ScriptIntelligenceField(safety_requires_approval)",
    displayOrder: next(),
  },
  {
    key: "safety.expired_claims",
    section: "SAFETY",
    userFacingQuestion: "Are there offers, prices, or results that have expired?",
    helperText: null,
    example: null,
    answerType: "LONG_TEXT",
    options: null,
    requiredLevel: "OPTIONAL",
    scriptImpacts: ["SAFETY"],
    destinationEntity: "ScriptIntelligenceField",
    destinationField: "safety_expired_claims",
    conditionalLogic: null,
    plainLanguageLabel: "Expired claims",
    expertLabel: "ScriptIntelligenceField(safety_expired_claims)",
    displayOrder: next(),
  },
];
